Repository heig-AMT/stack, pull requests merged in 2020-10, with the labels that each got.

#100 Create LINKS.md
  references/LINKS.md
Labels: documentation

#105 Question answering
  src/main/java/ch/heigvd/amt/stack/application/authentication/AuthenticationFacade.java
  src/main/java/ch/heigvd/amt/stack/application/question/QuestionFacade.java
  src/main/java/ch/heigvd/amt/stack/application/question/dto/QuestionDTO.java
  src/main/java/ch/heigvd/amt/stack/application/question/dto/QuestionIdDTO.java
  src/main/java/ch/heigvd/amt/stack/domain/authentication/CredentialId.java
  src/main/java/ch/heigvd/amt/stack/domain/authentication/SessionId.java
  src/main/java/ch/heigvd/amt/stack/domain/question/QuestionId.java
  src/main/java/ch/heigvd/amt/stack/infrastructure/persistence/database/JdbcAnswerRepository.java
  src/main/java/ch/heigvd/amt/stack/infrastructure/persistence/database/JdbcSessionRepository.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/AnswerCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/question/AskCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/filter/AuthorizationFilter.java
  src/main/java/ch/heigvd/amt/stack/ui/web/views/error/Error404View.java
  src/main/java/ch/heigvd/amt/stack/ui/web/views/question/QuestionView.java
  src/main/webapp/WEB-INF/views/ask.jsp
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
  src/main/webapp/WEB-INF/views/fragments/navigation.jsp
  src/main/webapp/WEB-INF/views/fragments/question.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/question.jsp
  src/main/webapp/WEB-INF/views/register.jsp
  src/test/java/ch/heigvd/amt/stack/application/answer/AnswerFacadeIntegration.java
Labels: enhancement

#109 Add voting CSS (with mocked data)
  src/main/java/ch/heigvd/amt/stack/application/answer/AnswerFacade.java
  src/main/java/ch/heigvd/amt/stack/application/answer/dto/AnswerDTO.java
  src/main/java/ch/heigvd/amt/stack/application/question/QuestionFacade.java
  src/main/java/ch/heigvd/amt/stack/application/question/query/SingleAnswerQuery.java
  src/main/java/ch/heigvd/amt/stack/infrastructure/persistence/database/JdbcVoteRepository.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/VoteCommandEndpoint.java
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
  src/main/webapp/WEB-INF/views/question.jsp
  src/main/webapp/assets/vote.svg
  src/test/java/ch/heigvd/amt/stack/application/answer/AnswerFacadeIntegration.java
  src/test/java/ch/heigvd/amt/stack/application/question/QuestionFacadeIntegration.java
  src/test/java/ch/heigvd/amt/stack/infrastructure/persistence/memory/InMemoryCredentialRepositoryTest.java
Labels: enhancement

#114 Remove disabled property from answering button
  src/main/webapp/WEB-INF/views/question.jsp
Labels: bug

#117 Fixed wrong authors showing up on answers
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
Labels: bug

#119 Move ResultSet to first position
  src/main/java/ch/heigvd/amt/stack/infrastructure/persistence/database/JdbcVoteRepository.java
Labels: bug

#121 Prevent logged out users from doing illegal actions
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
  src/main/webapp/WEB-INF/views/fragments/question.jsp
  src/main/webapp/WEB-INF/views/question.jsp
Labels: enhancement

#123 Add pretty colors to upvotes
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
  src/main/webapp/assets/downvote_red.svg
  src/main/webapp/assets/upvote_green.svg
Labels: enhancement

#130 Delete answer
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/DeleteAnswerCommandEndpoint.java
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
  src/main/webapp/WEB-INF/views/question.jsp
  src/main/webapp/assets/delete.svg
Labels: enhancement

#144 Display statistics on the home page
  src/main/java/ch/heigvd/amt/stack/ui/web/filter/ProvideConnectedFilter.java
  src/main/java/ch/heigvd/amt/stack/ui/web/filter/ProvideStatisticsFilter.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/index.jsp
  tests/e2e/tests/homepage_test.js
Labels: enhancement

#147 Profile page first iteration
  src/main/java/ch/heigvd/amt/stack/infrastructure/persistence/database/JdbcCredentialRepository.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/profile/ChangePasswordCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/filter/ProvideStatisticsFilter.java
  src/main/java/ch/heigvd/amt/stack/ui/web/views/profile/ProfilePageView.java
  src/main/webapp/WEB-INF/views/fragments/navigation.jsp
  src/main/webapp/WEB-INF/views/profile.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#154 Remove redirection URL on login / register
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/authentication/LoginCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/authentication/RegisterCommandEndpoint.java
Labels: bug

#155 Fix some CSS
  src/main/webapp/WEB-INF/views/404.jsp
  src/main/webapp/WEB-INF/views/ask.jsp
  src/main/webapp/WEB-INF/views/fragments/navigation.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/profile.jsp
  src/main/webapp/WEB-INF/views/question.jsp
  src/main/webapp/WEB-INF/views/register.jsp
  src/main/webapp/index.jsp
Labels: enhancement

#157 Add comments
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/CommentCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/DeleteCommentCommandEndpoint.java
  src/main/webapp/WEB-INF/views/fragments/addAnswer.jsp
  src/main/webapp/WEB-INF/views/fragments/addComment.jsp
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
  src/main/webapp/WEB-INF/views/fragments/authorAnswer.jsp
  src/main/webapp/WEB-INF/views/fragments/authorComment.jsp
  src/main/webapp/WEB-INF/views/fragments/authorQuestion.jsp
  src/main/webapp/WEB-INF/views/fragments/comment.jsp
  src/main/webapp/WEB-INF/views/fragments/question.jsp
  src/main/webapp/WEB-INF/views/fragments/shields.jsp
  src/main/webapp/WEB-INF/views/question.jsp
  src/main/webapp/assets/reply.svg
Labels: enhancement

#161 Add CSS to delete questions
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/question/DeleteQuestionCommandEndpoint.java
  src/main/webapp/WEB-INF/views/fragments/question.jsp
  src/main/webapp/WEB-INF/views/question.jsp
Labels: enhancement

#168 Add CSS and endpoints to (un)select answers
  src/main/java/ch/heigvd/amt/stack/infrastructure/persistence/database/JdbcQuestionRepository.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/SelectAnswerCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/UnselectAnswerCommandEndpoint.java
  src/main/webapp/WEB-INF/views/fragments/answer.jsp
  src/main/webapp/assets/check_gray.svg
  src/main/webapp/assets/check_green.svg
Labels: enhancement

#178 Custom error pages
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/AnswerCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/CommentCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/endpoints/answer/DeleteCommentCommandEndpoint.java
  src/main/java/ch/heigvd/amt/stack/ui/web/filter/AuthorizationFilter.java
  src/main/java/ch/heigvd/amt/stack/ui/web/views/error/Error404View.java
  src/main/java/ch/heigvd/amt/stack/ui/web/views/error/errorGenericView.java
  src/main/java/ch/heigvd/amt/stack/ui/web/views/question/QuestionView.java
  src/main/webapp/WEB-INF/views/404.jsp
  src/main/webapp/WEB-INF/views/error.jsp
  src/main/webapp/WEB-INF/views/fragments/navigation.jsp
  src/main/webapp/WEB-INF/views/profile.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/assets/authentication.svg
  src/main/webapp/assets/bug.svg
  src/main/webapp/assets/chilling.svg
  src/main/webapp/assets/engineer.svg
  src/main/webapp/assets/redirect.svg
  src/main/webapp/assets/serverdown.svg
  src/main/webapp/assets/tea.svg
Labels: enhancement
